name: TOC Generator
on: push
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-18.04
    steps:
      - uses: technote-space/toc-generator@v2
        with:
          TARGET_PATHS: "docs/*.md,docs/admin/*.md,.github/README.md,python/dbt-helper/*.md"
          TOC_TITLE: ""
          MAX_HEADER_LEVEL: 3
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          COMMIT_MESSAGE: "Generate Table of Contents in markdown files with GitHub Actions"
